# .goreleaser.yml
version: 2

before:
  hooks:
    - ./set-version.sh

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - "386"
      - amd64
      - arm64
    goarm:
      - "7"
    ignore:
      - goarch: "386"
        goos: darwin

archives:
  - format: tar.gz
    formats:
      - goos: windows
        format: zip

homebrew:
  - name: crusher
    repository:
      owner: JamesWoolfenden
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: "GitHub Action"
      email: action@github.com
    homepage: "https://github.com/JamesWoolfenden/crusher#readme"
    description: "crusher is a utility bigtable applications"
    install: |
      bin.install "crusher"
    test: |
      system "#{bin}/crusher", "--help"
